runtime: nodejs18

env_variables:
  NODE_ENV: production
  NEXTAUTH_URL: "https://your-app-name.appspot.com"
  NEXT_PUBLIC_CONVEX_URL: "${NEXT_PUBLIC_CONVEX_URL}"
  CONVEX_DEPLOYMENT: "${CONVEX_DEPLOYMENT}"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always
